additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/4894
  - "template-*"

files:
  - "!README.md"
  - "!docs/**"
  - "!colophon.yml"
  - "!docker-compose.yml"
  - "!.github/template-sync.yml"
