additional:
  - "template-*"

files:
  - "!.github/workflows/push.yml"
  - "!.gitignore"
  - "!**/template-sync.yml"
  - "!colophon.yml"
  - "!docker-compose.yml"
  - "!docs/**"
  - "!Makefile"
  - "!README.md"
