version: '3.8'

services:
  # ---- super-linter ---- #
  lint:
    image: github/super-linter:slim-v4
    volumes:
      - ./:/tmp/lint
    environment:
      LOG_LEVEL: 'ERROR'
      RUN_LOCAL: 'true'
      MULTI_STATUS: 'false'

  # ---- readme generator ---- #
  readme:
    image: pandoc/core:2.13
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml
