version: '3.8'

services:
  # ---- super-linter ---- #
  lint:
    image: github/super-linter:slim-v4
    volumes:
      - ./:/github/workspace
    environment:
      RUN_LOCAL: 'true'
      LOG_LEVEL: 'ERROR'
      MULTI_STATUS: 'false'
      VALIDATE_JSCPD: 'false'
      IGNORE_GITIGNORED_FILES: 'true'
      DEFAULT_WORKSPACE: /github/workspace
      FILTER_REGEX_EXCLUDE: '/github/workspace/README.md'

  # ---- readme generator ---- #
  readme:
    image: pandoc/core:2.13
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml
