# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: pull_request_target

on: pull_request_target

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/pull-request-target.yml@master
    secrets: inherit
    permissions: write-all
