ENABLE: ACTION,BASH,MAKEFILE,REPOSITORY,TERRAFORM,HTML,ENV,JAVASCRIPT,JSX,EDITORCONFIG,JSON,DOCKERFILE,MARKDOWN,YAML,CSS,OPENAPI,SQL
DISABLE_LINTERS:
  - JSON_PRETTIER
  - JAVASCRIPT_PRETTIER
  - YAML_PRETTIER
FLAVOR_SUGGESTIONS: false
LOG_LEVEL: INFO
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdown-lint.yml
