# ------------------------------------------------------------- #
# Note: this file is automatically managed in template-template #
# ------------------------------------------------------------- #

on: pull_request_target

name: pull_request_target

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    # security check: only run with dependabot PRs
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  template-sync:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-workflow-queue@v1.1

      - uses: actions/checkout@v2.3.4

      - uses: ahmadnassri/action-template-repository-sync@v1.6.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          dry-run: true
